// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItinerariesIndexController from "./itineraries_index_controller"
application.register("itineraries-index", ItinerariesIndexController)

import ItineraryAddProductsController from "./itinerary_add_products_controller"
application.register("itinerary-add-products", ItineraryAddProductsController)

import ItineraryShowController from "./itinerary_show_controller"
application.register("itinerary-show", ItineraryShowController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapShowController from "./map_show_controller"
application.register("map-show", MapShowController)
